name: Code Jest Testing
on: [push]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Test and upload coverage report
      env: # Or as an environment variable
        CODE_COV_TOKEN: ${{ secrets.CODE_COV }}
      run: |
        npm run test
        bash <(curl -s https://codecov.io/bash)
