name: Code Jest Testing
on: [push]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
    - name: Run Jest and Coverage
      env: # Or as an environment variable
        super_secret: ${{ secrets.CODE_COV }}
      run: npm run coverage
