name: Code Jest Testing
on: [push]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Test and upload coverage report
      env:
        CODECOV_TOKEN: ${{ secrets.CODE_COV }}
      run: npm run test
      run: bash <(curl -s https://codecov.io/bash)
